server:
  port: 8081 # 是eureka server的默认端口
eureka:
  server:
    enable-self-preservation: false #防止由于Eureka的机制导致Client被错误显示在线 仅在开发环境使用
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/ #这便是此eureka server的应用注册地址
    register-with-eureka: true #是否显示对server应用的注册
spring:
  application:
    name: eureka-demo

# eureka 8080/8081
# order 8083
# product 8082